### ISSUE TITLE
Unable to upload quizlet to anki

### ISSUE THREAD

**Issue by jlim022** [sviatoslav-lebediev/anki-quizlet-importer-extended#189]
**Describe the bug**
My quizlet keep failing to upload 
this one
https://quizlet.com/926675751/community-hygiene-1-flash-cards/?i=3nudoe&x=1jqt

**Additional context**
It comes up with unknown error and this box 
![Screenshot 2024-07-02 015134](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/174394255/cea2dfc2-fa32-4c55-99f7-92102d3e3f9c)

I tried with my other smaller quizlet too but it is coming with the same issue. It says unknown error and the box again with all that. Thank you.

**Comment by sviatoslav-lebediev** [comment]
Hi, could you try one more time, it looks like cloudflare started to detect my proxy :( I've released a new version,hope it helps but if not please let me know

**Comment by sviatoslav-lebediev** [comment]
if it still doesn't work - please use HTML MODE 
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/53e24a72-5121-434a-ad63-60edc46fe556)

**Comment by jlim022** [comment]
Hello, it just worked without HTML mode. Thank you so much :))

**Comment by sviatoslav-lebediev** [comment]
> Hello, it just worked without HTML mode. Thank you so much :))

yes, it's possible that for some users, it can import decks. It depends on your network connection. I would recommend trying to use your mobile network if it's possible.
Right now, the add-on tries to import data in this way
1. direct quizlet call. if cloudflare doesn't block your request - that's it
2. otherwise add-on calls my server and that server tries to bypass a cloudflare protection. but sometimes cloudflare changes something, and even my server can't fetch quizlet data :(

**Comment by kalli-git** [comment]
<img width="489" alt="Screen Shot 2024-07-23 at 9 32 31 PM" src="https://github.com/user-attachments/assets/9165b804-b68d-44e1-b19d-244f6ce872fc">
getting this screenshot when I just use quizlet URL and then still getting the unknown error screenshot when I do use the HTML box :( please advise!

**Comment by kalli-git** [comment]
nvm it seemed to work when You just upload the quizlet URL link to the top and check skip issues! in case anyone is having the same problem occur. Thank you for this add on!

**Comment by sviatoslav-lebediev** [comment]
> nvm it seemed to work when You just upload the quizlet URL link to the top and check skip issues! in case anyone is having the same problem occur. Thank you for this add on!

The only problem is that you may miss the audio. If you need the audio, please email me at moro.programmer@gmail.com, and I will send you a license key.

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, create a new one if you still have this error
