### ISSUE TITLE
Quizlet can't be imported

### ISSUE THREAD

**Issue by mahdihs123** [sviatoslav-lebediev/anki-quizlet-importer-extended#86]
The quizlets I try to import are not being processed by the mod. I have used this mod for a while now and recently it has been giving me unknown errors constantly. I have also updated to the most recent version of anki and still am running into this problem. 

one quizlet link I can't process is : https://quizlet.com/806874218/gi-secretions-flash-cards/?new

The unknown error is: Expecting value: line 1 column 1 (char 0). 

Please let me know how this can be fixed.

**Comment by ARPBlueSteel** [comment]
Same issue here

```
Expecting value: line 1 column 1 (char 0)
-----------------
```

Quizlet link is: https://quizlet.com/305727204/32-chromosomes-flash-cards/

Pasting html does not seem to fix the issue.

Version ⁨2.1.61 (0c1eaf4c)⁩, Windows 10

**Comment by OlegShevtsov1** [comment]
Same issue here

Expecting value: line 1 column 1 (char 0)
-----------------
Quizlet link is: https://quizlet.com/329740026/business-result-intermediate-unit-1-flash-cards

Pasting html does not seem to fix the issue.

Version ⁨2.1.64 (581f82c5)⁩, Linux Ubuntu


Please let me be aware if there is a workaround.

**Comment by sviatoslav-lebediev** [comment]
Hi, I've checked and I can import all decks that you guys sent. Maybe the problem is that you paste incorrect HTML? 
1. you need to enter a URL 
2. click on the `open html` button
3. take source from that page, **NOT FROM YOUR DECK PAGE**

If you don't need audio - uncheck the `Download audio` checkbox. It will work 100% because it doesn't require any additional info. If you paste just the URL the add-on needs to download that HTML page and the problem is that Quizlet from time to time based on some algorithms protects these pages using Cloudflare. 

here is a video how I've imported @OlegShevtsov1 deck

https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/49771432-b928-4ead-832d-d0106f006a87

**Comment by JSGandora** [comment]
> I am getting the same error:
> 
> ```
> Expecting value: line 1 column 1 (char 0)
> -----------------
> ```
> 
> The quizlet link i can't process is: https://quizlet.com/87443258/hebrew-vocabulary-essential-biblical-hebrew-lesson-18-flash-cards/
> 
> Additionally, when I try pasting the page html into the text box I get the same error.
> 
> I get the error on both Anki 2.1.35 and 2.1.49.

I saw @sviatoslav-lebediev's comment on the Anki plugin page about how Quizlet sometimes blocks requests. So I tried using a vpn and it worked the second time I tried importing.

**Comment by OlegShevtsov1** [comment]
I've imported. But the next time it has been not working.

**Comment by OlegShevtsov1** [comment]
I've been imported the other deck https://quizlet.com/212835488/vocabulary-business-result-intermediate-unit-2-flash-cards/

When I import the same the error is the previous too

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/10757507/6e910e7c-df97-4aa9-a1d4-699797ffc7e6)

**Comment by JSGandora** [comment]
> I've been imported the other deck https://quizlet.com/212835488/vocabulary-business-result-intermediate-unit-2-flash-cards/
> 
> When I import the same the error is the previous too
> 
> ![image](https://user-images.githubusercontent.com/10757507/242406784-6e910e7c-df97-4aa9-a1d4-699797ffc7e6.png)

Fwiw I get the same error when I tried to import using the Page html.

**Comment by OlegShevtsov1** [comment]
When it's the copy-paste it's the same error too.

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/10757507/c5926729-3945-4fd6-937b-c3aa3bc3bbf9)

**Comment by penpalcali** [comment]
I was importing decks just fine (probably converted 5 decks)  until about 20 minutes ago when I keep getting the same error as everyone above is and I have tried at least 10 times to convert it but I keep getting the same error 

<img width="609" alt="Screenshot 2023-05-31 at 2 02 36 PM" src="https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/110776966/b11e72d4-2a15-4e2a-a9c9-21dc8ff165af">

**Comment by JSGandora** [comment]
> I was importing decks just fine (probably converted 5 decks) until about 20 minutes ago when I keep getting the same error as everyone above is and I have tried at least 10 times to convert it but I keep getting the same error
> 
> <img alt="Screenshot 2023-05-31 at 2 02 36 PM" width="609" src="https://user-images.githubusercontent.com/110776966/242410706-b11e72d4-2a15-4e2a-a9c9-21dc8ff165af.png">

Perhaps try using a VPN to download the decks. It might take a few tries. It looks like you’re on mac - Proton VPN is installed by default I believe.

**Comment by sviatoslav-lebediev** [comment]
I would try to use a VPN as some guys proposed here + try to check `skip errors` when you use the `HTML` option but after that try to check if all images have been downloaded.

In a nutshell, the problem is that this add-on needs to download somehow data from the quizlet. 
Quizlet blocks sometimes requests (HTML, audio, images) using CloudFlare. I use some proxies that help to fetch data but because this add-on become quite popular I guess that proxy list can't handle all requests. Some free CloudFlare fixers that I've tried didn't work and I'm not ready to pay 100-200$ per month for paid solutions.
I'm going to try to use a few more approaches that maybe will help me to fix the problem with CloudFlare.

If you have some services or solutions that you think can help - let me know.

**Comment by mhujer** [comment]
What worked for me just to work around the "Captcha challenge..." error was to set `qlts` config value in Tools -> Addons -> Quizlet to Anki -> Config. As a value I used cookie with a same name from Chrome where I'm logged into Quizlet.

**Comment by sviatoslav-lebediev** [comment]
@mhujer good call, thx you. i will add this info to the add-on page

**Comment by OlegShevtsov1** [comment]
The error still here
`Expecting value: line 1 column 1 (char 0)`

I'm importing the flash cards without any blocker, VPN, restricted access in Chrome incognito mode
Could you please tip last solution of the issue

**Comment by sviatoslav-lebediev** [comment]
@OlegShevtsov1 I've released  a new version of the add-on, please update the add-on and try one more time

**Comment by JSGandora** [comment]
I updated the add-on but now I keep on getting the same error even after I connect to VPN. It also doesn't work when I copy the page html - I get the same error.

**Comment by sviatoslav-lebediev** [comment]
@JSGandora what error do you receive? 

As for the HTML mode
1. If your deck doesn't have images and you uncheck `Download audio` the add-on will not do any external calls
2. If you need audio or it has images the add-on will do calls because it needs to download these URLs. 
3. If some of the deck URLs (audio/image) are broken you can try to check `Skip errors` checkbox
 
I've tried to download your deck and I haven't seen any issues

[Hebrew Vocabulary Essential Biblical Hebrew lesson 18.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11786737/Hebrew.Vocabulary.Essential.Biblical.Hebrew.lesson.18.apkg.zip)

**Comment by sviatoslav-lebediev** [comment]
@JSGandora 
sorry, UI is not the best but you need to check this checkbox

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/f9ef9e70-caab-4f49-9162-c57e75ac0d31)

it's strange that your last try wasn't successful 
Could you try to install the version from this page https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/releases/tag/v2023.06.18 ?

p.s. here is your deck 
[Final Study_ Pual, Hiphil, Hophal, Hithpael Parsing Practice.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11792753/Final.Study_.Pual.Hiphil.Hophal.Hithpael.Parsing.Practice.apkg.zip)

**Comment by JSGandora** [comment]
I just tried installing the version of the add on from your link, and importing this deck: https://quizlet.com/87443339/hebrew-vocabulary-essential-biblical-hebrew-lesson-21-flash-cards/ but I still get the error:

![Screenshot 2023-06-19 at 7 10 33 PM](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/6230826/8074f753-c7c6-4627-b555-a1c5420c24ad)

Thank you for creating one of the decks for me!

**Comment by OlegShevtsov1** [comment]
It works fine for me from this update

**Comment by JSGandora** [comment]
@OlegShevtsov1  does importing a deck with pictures also work for you? Or just text?

**Comment by JSGandora** [comment]
Nevermind - the first time I tried I did not uninstall the add-on before reinstalling it, I thought installing it from the file would override it. Uninstalling the add-on and reinstalling it worked for me!

**Comment by OlegShevtsov1** [comment]
@JSGandora text with picture and audio

The desk for an example
https://quizlet.com/596690768/business-result-2nd-edition-intermediate-unit-1-flash-cards/ 

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/10757507/f3062411-c914-40de-8a19-2e959cb82f19)

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, if somebody still can't import decks, please create a new issue
